enum states
{
	normal = 0,
	tumble = 1,
	finishingblow = 2,
	ejected = 3,
	transitioncutscene = 4,
	fireass = 5,
	firemouth = 6,
	titlescreen = 7,
	hookshot = 8,
	tacklecharge = 9,
	cheeseball = 10,
	slap = 11,
	cheesepep = 12,
	cheesepepstick = 13,
	boxxedpep = 14,
	pistolaim = 15,
	climbwall = 16,
	knightpepslopes = 17,
	portal = 18,
	secondjump = 19,
	chainsawbump = 20,
	handstandjump = 21,
	gottreasure = 22,
	knightpep = 23,
	knightpepattack = 24,
	meteorpep = 25,
	bombpep = 26,
	grabbing = 27,
	chainsawpogo = 28,
	shotgunjump = 29,
	stunned = 30,
	highjump = 31,
	chainsaw = 32,
	facestomp = 33,
	mach4 = 34,
	timesup = 35,
	machroll = 36,
	shotgun = 37,
	pistol = 38,
	machfreefall = 39,
	thrown = 40,
	slam = 41,
	superslam = 42,
	skateboard = 43,
	grind = 44,
	grab = 45,
	punch = 46,
	backkick = 47,
	uppunch = 48,
	shoulder = 49,
	backbreaker = 50,
	bossdefeat = 51,
	pizzathrow = 52,
	bossintro = 53,
	gameover = 54,
	keyget = 55,
	tackle = 56,
	jump = 57,
	ladder = 58,
	slipnslide = 59,
	comingoutdoor = 60,
	smirk = 61,
	Sjump = 62,
	victory = 63,
	Sjumpprep = 64,
	crouch = 65,
	crouchjump = 66,
	crouchslide = 67,
	mach1 = 68,
	mach2 = 69,
	machslide = 70,
	bump = 71,
	hurt = 72,
	freefall = 73,
	hang = 74,
	unknown_75 = 75,
	freefallland = 76,
	door = 77,
	barrelcrouch = 78,
	barrelfloat = 79,
	barrelmach2 = 80,
	barrelmach1 = 81,
	barrelfall = 82,
	barrelnormal = 83,
	barrelslipnslide = 84,
	barrelroll = 85,
	current = 86,
	boulder = 87,
	runonball = 88,
	mach3 = 89,
	freefallprep = 90,
	Sjumpland = 91,
	idle = 92,
	bounce = 93,
	charge = 94,
	pizzagoblin_throw = 95,
	turn = 96,
	hitceilling = 97,
	hitwall = 98,
	unknown_99 = 99,
	walk = 100,
	unknown_101 = 101,
	land = 102,
	hit = 103,
	stun = 104,
	unknown_105 = 105,
	unknown_106 = 106,
	grabbed = 107,
}


ini_open("saveData.ini");
global.deserthighscore = ini_read_string("Highscore", "desert", 0);
global.mansionhighscore = ini_read_string("Highscore", "mansion", 0);
global.factoryhighscore = ini_read_string("Highscore", "factory", 0);
global.sewerhighscore = ini_read_string("Highscore", "sewer", 0);
global.freezerhighscore = ini_read_string("Highscore", "freezer", 0);
global.entrancehighscore = ini_read_string("Highscore", "entrance", 0);
global.medievalhighscore = ini_read_string("Highscore", "medieval", 0);
global.deserttoppin1 = ini_read_string("Toppin", "desert1", 0);
global.deserttoppin2 = ini_read_string("Toppin", "desert2", 0);
global.deserttoppin3 = ini_read_string("Toppin", "desert3", 0);
global.deserttoppin4 = ini_read_string("Toppin", "desert4", 0);
global.deserttoppin5 = ini_read_string("Toppin", "desert5", 0);
global.mansiontoppin1 = ini_read_string("Toppin", "mansion1", 0);
global.mansiontoppin2 = ini_read_string("Toppin", "mansion2", 0);
global.mansiontoppin3 = ini_read_string("Toppin", "mansion3", 0);
global.mansiontoppin4 = ini_read_string("Toppin", "mansion4", 0);
global.mansiontoppin5 = ini_read_string("Toppin", "mansion5", 0);
global.factorytoppin1 = ini_read_string("Toppin", "factory1", 0);
global.factorytoppin2 = ini_read_string("Toppin", "factory2", 0);
global.factorytoppin3 = ini_read_string("Toppin", "factory3", 0);
global.factorytoppin4 = ini_read_string("Toppin", "factory4", 0);
global.factorytoppin5 = ini_read_string("Toppin", "factory5", 0);
global.sewertoppin1 = ini_read_string("Toppin", "sewer1", 0);
global.sewertoppin2 = ini_read_string("Toppin", "sewer2", 0);
global.sewertoppin3 = ini_read_string("Toppin", "sewer3", 0);
global.sewertoppin4 = ini_read_string("Toppin", "sewer4", 0);
global.sewertoppin5 = ini_read_string("Toppin", "sewer5", 0);
global.freezertoppin1 = ini_read_string("Toppin", "freezer1", 0);
global.freezertoppin2 = ini_read_string("Toppin", "freezer2", 0);
global.freezertoppin3 = ini_read_string("Toppin", "freezer3", 0);
global.freezertoppin4 = ini_read_string("Toppin", "freezer4", 0);
global.freezertoppin5 = ini_read_string("Toppin", "freezer5", 0);
global.entrancetoppin1 = ini_read_string("Toppin", "entrance1", 0);
global.entrancetoppin2 = ini_read_string("Toppin", "entrance2", 0);
global.entrancetoppin3 = ini_read_string("Toppin", "entrance3", 0);
global.entrancetoppin4 = ini_read_string("Toppin", "entrance4", 0);
global.entrancetoppin5 = ini_read_string("Toppin", "entrance5", 0);
global.medievaltoppin1 = ini_read_string("Toppin", "medieval1", 0);
global.medievaltoppin2 = ini_read_string("Toppin", "medieval2", 0);
global.medievaltoppin3 = ini_read_string("Toppin", "medieval3", 0);
global.medievaltoppin4 = ini_read_string("Toppin", "medieval4", 0);
global.medievaltoppin5 = ini_read_string("Toppin", "medieval5", 0);
ini_close();
